### ISSUE TITLE
Feature request-  multiple results  by titles

### ISSUE THREAD

**Issue by eviatar-ben** [The-Kor/www#33]
display multiple results  by titles:

e.g.-
![image](https://user-images.githubusercontent.com/82065601/122886593-c5870b80-d348-11eb-8c68-66ac9d044d16.png)

instead  of one absolute result.

including an interactive ability to travers between the different results.

**Comment by eviatar-ben** [comment]
"Results Board" feature.

**Comment by eviatar-ben** [comment]
This feature also known as "Results Board".

**Comment by The-Kor** [comment]
Closed - this was implemented in Results Board Implementation #32 Pull Request.
